
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox2;

	private global::Gtk.VBox vbox4;

	private global::Gtk.Entry displayMain;

	private global::Gtk.HSeparator hseparator2;

	private global::Gtk.HBox columns;

	private global::Gtk.VButtonBox columnButton1;

	private global::Gtk.Button reset;

	private global::Gtk.Button button7;

	private global::Gtk.Button button4;

	private global::Gtk.Button button1;

	private global::Gtk.Button button;

	private global::Gtk.VButtonBox columnButton2;

	private global::Gtk.Button clearEntry;

	private global::Gtk.Button button8;

	private global::Gtk.Button button5;

	private global::Gtk.Button button2;

	private global::Gtk.Button button20;

	private global::Gtk.VButtonBox columnButton3;

	private global::Gtk.Button button450;

	private global::Gtk.Button button9;

	private global::Gtk.Button button6;

	private global::Gtk.Button button3;

	private global::Gtk.Button buttonEquals;

	private global::Gtk.VButtonBox columnButton4;

	private global::Gtk.Button deleteButton;

	private global::Gtk.Button divide;

	private global::Gtk.Button multiply;

	private global::Gtk.Button subtract;

	private global::Gtk.Button add;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.BorderWidth = ((uint)(15));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox2 = new global::Gtk.VBox();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.vbox4 = new global::Gtk.VBox();
		this.vbox4.Name = "vbox4";
		this.vbox4.Spacing = 6;
		// Container child vbox4.Gtk.Box+BoxChild
		this.displayMain = new global::Gtk.Entry();
		this.displayMain.Name = "displayMain";
		this.displayMain.IsEditable = false;
		this.displayMain.InvisibleChar = '•';
		this.vbox4.Add(this.displayMain);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.displayMain]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.hseparator2 = new global::Gtk.HSeparator();
		this.hseparator2.Name = "hseparator2";
		this.vbox4.Add(this.hseparator2);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.hseparator2]));
		w2.Position = 1;
		w2.Expand = false;
		w2.Fill = false;
		this.vbox2.Add(this.vbox4);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.vbox4]));
		w3.Position = 0;
		w3.Expand = false;
		w3.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.columns = new global::Gtk.HBox();
		this.columns.Name = "columns";
		this.columns.Homogeneous = true;
		this.columns.Spacing = 6;
		// Container child columns.Gtk.Box+BoxChild
		this.columnButton1 = new global::Gtk.VButtonBox();
		this.columnButton1.Name = "columnButton1";
		this.columnButton1.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(1));
		// Container child columnButton1.Gtk.ButtonBox+ButtonBoxChild
		this.reset = new global::Gtk.Button();
		this.reset.CanFocus = true;
		this.reset.Name = "reset";
		this.reset.UseUnderline = true;
		this.reset.Label = global::Mono.Unix.Catalog.GetString("C");
		this.columnButton1.Add(this.reset);
		global::Gtk.ButtonBox.ButtonBoxChild w4 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.columnButton1[this.reset]));
		w4.Expand = false;
		w4.Fill = false;
		// Container child columnButton1.Gtk.ButtonBox+ButtonBoxChild
		this.button7 = new global::Gtk.Button();
		this.button7.CanFocus = true;
		this.button7.Name = "button7";
		this.button7.UseUnderline = true;
		this.button7.Label = global::Mono.Unix.Catalog.GetString("7");
		this.columnButton1.Add(this.button7);
		global::Gtk.ButtonBox.ButtonBoxChild w5 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.columnButton1[this.button7]));
		w5.Position = 1;
		w5.Expand = false;
		w5.Fill = false;
		// Container child columnButton1.Gtk.ButtonBox+ButtonBoxChild
		this.button4 = new global::Gtk.Button();
		this.button4.CanFocus = true;
		this.button4.Name = "button4";
		this.button4.UseUnderline = true;
		this.button4.Label = global::Mono.Unix.Catalog.GetString("4");
		this.columnButton1.Add(this.button4);
		global::Gtk.ButtonBox.ButtonBoxChild w6 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.columnButton1[this.button4]));
		w6.Position = 2;
		w6.Expand = false;
		w6.Fill = false;
		// Container child columnButton1.Gtk.ButtonBox+ButtonBoxChild
		this.button1 = new global::Gtk.Button();
		this.button1.CanFocus = true;
		this.button1.Name = "button1";
		this.button1.UseUnderline = true;
		this.button1.Label = global::Mono.Unix.Catalog.GetString("1");
		this.columnButton1.Add(this.button1);
		global::Gtk.ButtonBox.ButtonBoxChild w7 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.columnButton1[this.button1]));
		w7.Position = 3;
		w7.Expand = false;
		w7.Fill = false;
		// Container child columnButton1.Gtk.ButtonBox+ButtonBoxChild
		this.button = new global::Gtk.Button();
		this.button.CanFocus = true;
		this.button.Name = "button";
		this.button.UseUnderline = true;
		this.button.Label = global::Mono.Unix.Catalog.GetString("0");
		this.columnButton1.Add(this.button);
		global::Gtk.ButtonBox.ButtonBoxChild w8 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.columnButton1[this.button]));
		w8.Position = 4;
		w8.Expand = false;
		w8.Fill = false;
		this.columns.Add(this.columnButton1);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.columns[this.columnButton1]));
		w9.Position = 0;
		w9.Expand = false;
		w9.Fill = false;
		// Container child columns.Gtk.Box+BoxChild
		this.columnButton2 = new global::Gtk.VButtonBox();
		this.columnButton2.Name = "columnButton2";
		this.columnButton2.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(1));
		// Container child columnButton2.Gtk.ButtonBox+ButtonBoxChild
		this.clearEntry = new global::Gtk.Button();
		this.clearEntry.CanFocus = true;
		this.clearEntry.Name = "clearEntry";
		this.clearEntry.UseUnderline = true;
		this.clearEntry.Label = global::Mono.Unix.Catalog.GetString("CE");
		this.columnButton2.Add(this.clearEntry);
		global::Gtk.ButtonBox.ButtonBoxChild w10 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.columnButton2[this.clearEntry]));
		w10.Expand = false;
		w10.Fill = false;
		// Container child columnButton2.Gtk.ButtonBox+ButtonBoxChild
		this.button8 = new global::Gtk.Button();
		this.button8.CanFocus = true;
		this.button8.Name = "button8";
		this.button8.UseUnderline = true;
		this.button8.Label = global::Mono.Unix.Catalog.GetString("8");
		this.columnButton2.Add(this.button8);
		global::Gtk.ButtonBox.ButtonBoxChild w11 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.columnButton2[this.button8]));
		w11.Position = 1;
		w11.Expand = false;
		w11.Fill = false;
		// Container child columnButton2.Gtk.ButtonBox+ButtonBoxChild
		this.button5 = new global::Gtk.Button();
		this.button5.CanFocus = true;
		this.button5.Name = "button5";
		this.button5.UseUnderline = true;
		this.button5.Label = global::Mono.Unix.Catalog.GetString("5");
		this.columnButton2.Add(this.button5);
		global::Gtk.ButtonBox.ButtonBoxChild w12 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.columnButton2[this.button5]));
		w12.Position = 2;
		w12.Expand = false;
		w12.Fill = false;
		// Container child columnButton2.Gtk.ButtonBox+ButtonBoxChild
		this.button2 = new global::Gtk.Button();
		this.button2.CanFocus = true;
		this.button2.Name = "button2";
		this.button2.UseUnderline = true;
		this.button2.Label = global::Mono.Unix.Catalog.GetString("2");
		this.columnButton2.Add(this.button2);
		global::Gtk.ButtonBox.ButtonBoxChild w13 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.columnButton2[this.button2]));
		w13.Position = 3;
		w13.Expand = false;
		w13.Fill = false;
		// Container child columnButton2.Gtk.ButtonBox+ButtonBoxChild
		this.button20 = new global::Gtk.Button();
		this.button20.CanFocus = true;
		this.button20.Name = "button20";
		this.button20.UseUnderline = true;
		this.button20.Label = global::Mono.Unix.Catalog.GetString(",");
		this.columnButton2.Add(this.button20);
		global::Gtk.ButtonBox.ButtonBoxChild w14 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.columnButton2[this.button20]));
		w14.Position = 4;
		w14.Expand = false;
		w14.Fill = false;
		this.columns.Add(this.columnButton2);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.columns[this.columnButton2]));
		w15.Position = 1;
		w15.Expand = false;
		w15.Fill = false;
		// Container child columns.Gtk.Box+BoxChild
		this.columnButton3 = new global::Gtk.VButtonBox();
		this.columnButton3.Name = "columnButton3";
		this.columnButton3.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(1));
		// Container child columnButton3.Gtk.ButtonBox+ButtonBoxChild
		this.button450 = new global::Gtk.Button();
		this.button450.CanFocus = true;
		this.button450.Name = "button450";
		this.button450.UseUnderline = true;
		this.button450.Label = global::Mono.Unix.Catalog.GetString("+/-");
		this.columnButton3.Add(this.button450);
		global::Gtk.ButtonBox.ButtonBoxChild w16 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.columnButton3[this.button450]));
		w16.Expand = false;
		w16.Fill = false;
		// Container child columnButton3.Gtk.ButtonBox+ButtonBoxChild
		this.button9 = new global::Gtk.Button();
		this.button9.CanFocus = true;
		this.button9.Name = "button9";
		this.button9.UseUnderline = true;
		this.button9.Label = global::Mono.Unix.Catalog.GetString("9");
		this.columnButton3.Add(this.button9);
		global::Gtk.ButtonBox.ButtonBoxChild w17 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.columnButton3[this.button9]));
		w17.Position = 1;
		w17.Expand = false;
		w17.Fill = false;
		// Container child columnButton3.Gtk.ButtonBox+ButtonBoxChild
		this.button6 = new global::Gtk.Button();
		this.button6.CanFocus = true;
		this.button6.Name = "button6";
		this.button6.UseUnderline = true;
		this.button6.Label = global::Mono.Unix.Catalog.GetString("6");
		this.columnButton3.Add(this.button6);
		global::Gtk.ButtonBox.ButtonBoxChild w18 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.columnButton3[this.button6]));
		w18.Position = 2;
		w18.Expand = false;
		w18.Fill = false;
		// Container child columnButton3.Gtk.ButtonBox+ButtonBoxChild
		this.button3 = new global::Gtk.Button();
		this.button3.CanFocus = true;
		this.button3.Name = "button3";
		this.button3.UseUnderline = true;
		this.button3.Label = global::Mono.Unix.Catalog.GetString("3");
		this.columnButton3.Add(this.button3);
		global::Gtk.ButtonBox.ButtonBoxChild w19 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.columnButton3[this.button3]));
		w19.Position = 3;
		w19.Expand = false;
		w19.Fill = false;
		// Container child columnButton3.Gtk.ButtonBox+ButtonBoxChild
		this.buttonEquals = new global::Gtk.Button();
		this.buttonEquals.CanFocus = true;
		this.buttonEquals.Name = "buttonEquals";
		this.buttonEquals.UseUnderline = true;
		this.buttonEquals.Label = global::Mono.Unix.Catalog.GetString("=");
		this.columnButton3.Add(this.buttonEquals);
		global::Gtk.ButtonBox.ButtonBoxChild w20 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.columnButton3[this.buttonEquals]));
		w20.Position = 4;
		w20.Expand = false;
		w20.Fill = false;
		this.columns.Add(this.columnButton3);
		global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.columns[this.columnButton3]));
		w21.Position = 2;
		w21.Expand = false;
		w21.Fill = false;
		// Container child columns.Gtk.Box+BoxChild
		this.columnButton4 = new global::Gtk.VButtonBox();
		this.columnButton4.Name = "columnButton4";
		this.columnButton4.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(1));
		// Container child columnButton4.Gtk.ButtonBox+ButtonBoxChild
		this.deleteButton = new global::Gtk.Button();
		this.deleteButton.CanFocus = true;
		this.deleteButton.Name = "deleteButton";
		this.deleteButton.UseUnderline = true;
		this.deleteButton.Label = global::Mono.Unix.Catalog.GetString("DEL");
		this.columnButton4.Add(this.deleteButton);
		global::Gtk.ButtonBox.ButtonBoxChild w22 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.columnButton4[this.deleteButton]));
		w22.Expand = false;
		w22.Fill = false;
		// Container child columnButton4.Gtk.ButtonBox+ButtonBoxChild
		this.divide = new global::Gtk.Button();
		this.divide.CanFocus = true;
		this.divide.Name = "divide";
		this.divide.UseUnderline = true;
		this.divide.Label = global::Mono.Unix.Catalog.GetString("/");
		this.columnButton4.Add(this.divide);
		global::Gtk.ButtonBox.ButtonBoxChild w23 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.columnButton4[this.divide]));
		w23.Position = 1;
		w23.Expand = false;
		w23.Fill = false;
		// Container child columnButton4.Gtk.ButtonBox+ButtonBoxChild
		this.multiply = new global::Gtk.Button();
		this.multiply.CanFocus = true;
		this.multiply.Name = "multiply";
		this.multiply.UseUnderline = true;
		this.multiply.Label = global::Mono.Unix.Catalog.GetString("x");
		this.columnButton4.Add(this.multiply);
		global::Gtk.ButtonBox.ButtonBoxChild w24 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.columnButton4[this.multiply]));
		w24.Position = 2;
		w24.Expand = false;
		w24.Fill = false;
		// Container child columnButton4.Gtk.ButtonBox+ButtonBoxChild
		this.subtract = new global::Gtk.Button();
		this.subtract.CanFocus = true;
		this.subtract.Name = "subtract";
		this.subtract.UseUnderline = true;
		this.subtract.Label = global::Mono.Unix.Catalog.GetString("-");
		this.columnButton4.Add(this.subtract);
		global::Gtk.ButtonBox.ButtonBoxChild w25 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.columnButton4[this.subtract]));
		w25.Position = 3;
		w25.Expand = false;
		w25.Fill = false;
		// Container child columnButton4.Gtk.ButtonBox+ButtonBoxChild
		this.add = new global::Gtk.Button();
		this.add.CanFocus = true;
		this.add.Name = "add";
		this.add.UseUnderline = true;
		this.add.Label = "+";
		this.columnButton4.Add(this.add);
		global::Gtk.ButtonBox.ButtonBoxChild w26 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.columnButton4[this.add]));
		w26.Position = 4;
		w26.Expand = false;
		w26.Fill = false;
		this.columns.Add(this.columnButton4);
		global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.columns[this.columnButton4]));
		w27.Position = 3;
		w27.Expand = false;
		w27.Fill = false;
		this.vbox2.Add(this.columns);
		global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.columns]));
		w28.Position = 1;
		this.Add(this.vbox2);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 424;
		this.DefaultHeight = 394;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.reset.Clicked += new global::System.EventHandler(this.clickButtonReset);
		this.button7.Clicked += new global::System.EventHandler(this.ClickNumber);
		this.button4.Clicked += new global::System.EventHandler(this.ClickNumber);
		this.button1.Clicked += new global::System.EventHandler(this.ClickNumber);
		this.button.Clicked += new global::System.EventHandler(this.ClickNumber);
		this.clearEntry.Clicked += new global::System.EventHandler(this.ClearEntry);
		this.button8.Clicked += new global::System.EventHandler(this.ClickNumber);
		this.button5.Clicked += new global::System.EventHandler(this.ClickNumber);
		this.button2.Clicked += new global::System.EventHandler(this.ClickNumber);
		this.button20.Clicked += new global::System.EventHandler(this.ClickNumber);
		this.button450.Clicked += new global::System.EventHandler(this.PrependMinus);
		this.button9.Clicked += new global::System.EventHandler(this.ClickNumber);
		this.button6.Clicked += new global::System.EventHandler(this.ClickNumber);
		this.button3.Clicked += new global::System.EventHandler(this.ClickNumber);
		this.buttonEquals.Clicked += new global::System.EventHandler(this.clickButtonEquals);
		this.deleteButton.Clicked += new global::System.EventHandler(this.clickButtonDel);
		this.divide.Clicked += new global::System.EventHandler(this.ClickButtonDivide);
		this.multiply.Clicked += new global::System.EventHandler(this.ClickButtonMultiply);
		this.subtract.Clicked += new global::System.EventHandler(this.ClickButtonSubstract);
		this.add.Clicked += new global::System.EventHandler(this.clickButtonAdd);
	}
}
